// @generated by tools/compile_app_db.py; do not edit.

pub(crate) static APP_DB: &[AppDbEntry] = &[
    AppDbEntry {
        executables: &[
            AppDbExecutable {
                filename: "rich4.exe",
            },
        ],
        required_assets: &[
            AppDbRequiredAsset {
                name: "Media",
                asset_type: "directory",
                locator: "named-directory",
                mount: Some(AppDbMount { drive: 'D', device: "cdrom" }),
            },
        ],
    },
];
